# Generated by Django 4.2.16 on 2024-11-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='to_do_list',
            options={'ordering': ['-created_on']},
        ),
    ]
