# Generated by Django 4.2.16 on 2024-12-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_alter_to_do_list_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
